repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check .
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format --check
        entry: uv run ruff format --check .
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: uv run pytest tests/
        language: system
        types: [python]