repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check .
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format --check
        entry: uv run ruff format --check .
        language: system
        types: [python]

      - id: pytest
        name: pytest with coverage
        entry: bash -c "PYTHONPATH=$(pwd) uv run pytest tests/ --cov=src --cov-report=term-missing --cov-fail-under=90"
        language: system
        types: [python]